const songs = [

["Married Life","Michael Giacchino","Film",1,"Relaxing","Piano"],
["Minuet in G","J.S. Bach","Classical",1,"Emotional","Piano"],
["Canon in D (Easy)","Pachelbel","Classical",1,"Emotional","Piano"],
["Let It Be","The Beatles","Rock",1,"Emotional","Piano"],
["We Will Rock You","Queen","Rock",1,"Energetic","Piano"],
["Ode to Joy","Beethoven","Classical",1,"Relaxing","Piano"],
["Stand By Me","Ben E. King","Pop",1,"Relaxing","Piano"],
["Riptide","Vance Joy","Pop",1,"Energetic","Piano"],
["Perfect","Ed Sheeran","Pop",1,"Emotional","Piano"],
["Let It Go","Idina Menzel","Film",1,"Energetic","Piano"],

["River Flows in You","Yiruma","Classical",2,"Relaxing","Piano"],
["Clocks","Coldplay","Pop",2,"Energetic","Piano"],
["Canon in D","Pachelbel","Classical",2,"Relaxing","Piano"],
["Time","Hans Zimmer","Film",2,"Emotional","Piano"],

["Interstellar Theme","Hans Zimmer","Film",3,"Emotional","Piano"],
["Billie Jean","Michael Jackson","Pop",3,"Energetic","Piano"],
["Viva La Vida","Coldplay","Rock",3,"Emotional","Piano"],
["Someone Like You","Adele","Pop",3,"Emotional","Piano"],
["The Scientist","Coldplay","Rock",3,"Emotional","Piano"],
["Test Drive","John Powell","Film",3,"Energetic","Piano"],

["Bohemian Rhapsody","Queen","Rock",4,"Energetic","Piano"],
["Sweet Child O' Mine","Guns N' Roses","Rock",4,"Energetic","Piano"],
["Hotel California","Eagles","Rock",4,"Relaxing","Piano"],
["Experience","Ludovico Einaudi","Classical",4,"Emotional","Piano"],
["He's a Pirate","Klaus Badelt","Film",4,"Energetic","Piano"],

["Moonlight Sonata","Beethoven","Classical",5,"Emotional","Piano"],
["Clair de Lune","Debussy","Classical",5,"Relaxing","Piano"],
["Nocturne Op.9 No.2","Chopin","Classical",5,"Emotional","Piano"],
["Stairway to Heaven","Led Zeppelin","Rock",5,"Emotional","Piano"],

["Comptine d'un autre été","Yann Tiersen","Classical",2,"Relaxing","Piano"],
["Nuvole Bianche","Ludovico Einaudi","Classical",3,"Emotional","Piano"],
["Una Mattina","Ludovico Einaudi","Classical",3,"Relaxing","Piano"],
["I Giorni","Ludovico Einaudi","Classical",3,"Emotional","Piano"],
["Le Onde","Ludovico Einaudi","Classical",4,"Relaxing","Piano"],

["Gymnopédie No.1","Erik Satie","Classical",2,"Relaxing","Piano"],
["Gnossienne No.1","Erik Satie","Classical",3,"Relaxing","Piano"],
["Prelude in C Major","J.S. Bach","Classical",2,"Relaxing","Piano"],
["Arabesque No.1","Claude Debussy","Classical",4,"Relaxing","Piano"],
["Waltz in A Minor","Frédéric Chopin","Classical",3,"Emotional","Piano"],

["Prelude Op.28 No.4","Frédéric Chopin","Classical",3,"Emotional","Piano"],
["Raindrop Prelude","Frédéric Chopin","Classical",4,"Relaxing","Piano"],
["Liebestraum No.3","Franz Liszt","Classical",5,"Emotional","Piano"],
["Hungarian Rhapsody No.2","Franz Liszt","Classical",5,"Energetic","Piano"],
["Turkish March","W.A. Mozart","Classical",3,"Energetic","Piano"],

["Pathetique Sonata","Ludwig van Beethoven","Classical",5,"Emotional","Piano"],
["The Entertainer","Scott Joplin","Classical",3,"Energetic","Piano"],
["Maple Leaf Rag","Scott Joplin","Classical",4,"Energetic","Piano"],
["Sonatina in C","Muzio Clementi","Classical",2,"Relaxing","Piano"],
["Largo from New World Symphony","Antonín Dvořák","Classical",3,"Emotional","Piano"],

["Cornfield Chase","Hans Zimmer","Film",3,"Emotional","Piano"],
["Day One","Hans Zimmer","Film",3,"Relaxing","Piano"],
["Now We Are Free","Hans Zimmer","Film",4,"Emotional","Piano"],
["Chevaliers de Sangreal","Hans Zimmer","Film",5,"Energetic","Piano"],
["Hedwig's Theme","John Williams","Film",1,"Emotional","Piano"],

["Jurassic Park Theme","John Williams","Film",3,"Emotional","Piano"],
["Star Wars Main Theme","John Williams","Film",3,"Energetic","Piano"],
["The Imperial March","John Williams","Film",3,"Energetic","Piano"],
["One Summer's Day","Joe Hisaishi","Film",3,"Relaxing","Piano"],
["Merry-Go-Round of Life","Joe Hisaishi","Film",4,"Emotional","Piano"],

["Howl's Moving Castle Theme","Joe Hisaishi","Film",4,"Relaxing","Piano"],
["Marry Me","Train","Pop",2,"Relaxing","Piano"],
["Photograph","Ed Sheeran","Pop",2,"Emotional","Piano"],
["Thinking Out Loud","Ed Sheeran","Pop",2,"Relaxing","Piano"],
["Shallow","Lady Gaga","Pop",3,"Emotional","Piano"],

["Easy On Me","Adele","Pop",2,"Emotional","Piano"],
["Hello","Adele","Pop",3,"Emotional","Piano"],
["Someone You Loved","Lewis Capaldi","Pop",2,"Emotional","Piano"],
["Fix You","Coldplay","Rock",3,"Emotional","Piano"],
["Yellow","Coldplay","Rock",2,"Relaxing","Piano"],

["Paradise","Coldplay","Rock",3,"Energetic","Piano"],
["Demons","Imagine Dragons","Rock",2,"Emotional","Piano"],
["Radioactive","Imagine Dragons","Rock",3,"Energetic","Piano"],
["Nothing Else Matters","Metallica","Rock",4,"Emotional","Piano"],
["Don't Stop Believin'","Journey","Rock",3,"Energetic","Piano"],

["Sweden","C418","Film",2,"Relaxing","Piano"],
["Wet Hands","C418","Film",2,"Relaxing","Piano"],
["To Zanarkand","Nobuo Uematsu","Film",4,"Emotional","Piano"],
["Dragonborn","Jeremy Soule","Film",4,"Energetic","Piano"],
["Ezio's Family","Jesper Kyd","Film",4,"Emotional","Piano"],

["Hallelujah","Leonard Cohen","Pop",1,"Emotional","Piano"],
["Imagine","John Lennon","Pop",1,"Relaxing","Piano"],
["Count on Me","Bruno Mars","Pop",1,"Relaxing","Piano"],
["A Thousand Years","Christina Perri","Pop",1,"Emotional","Piano"],
["All of Me","John Legend","Pop",1,"Emotional","Piano"],
["Love Story","Taylor Swift","Pop",1,"Emotional","Piano"],
["You Are My Sunshine","Traditional","Pop",1,"Relaxing","Piano"],
["Can't Help Falling in Love","Elvis Presley","Pop",1,"Emotional","Piano"],
["Lean on Me","Bill Withers","Pop",1,"Relaxing","Piano"],
["What a Wonderful World","Louis Armstrong","Pop",1,"Relaxing","Piano"],

["The Lion Sleeps Tonight","The Tokens","Pop",1,"Energetic","Piano"],
["Happy Birthday","Traditional","Pop",1,"Relaxing","Piano"],
["Twinkle Twinkle Little Star","Traditional","Classical",1,"Relaxing","Piano"],
["Greensleeves","Traditional","Classical",1,"Relaxing","Piano"],
["Scarborough Fair","Traditional","Classical",1,"Emotional","Piano"],

["Morning Mood","Edvard Grieg","Classical",1,"Relaxing","Piano"],
["Simple Gifts","Traditional","Classical",1,"Relaxing","Piano"],
["Aura Lee","Traditional","Classical",1,"Relaxing","Piano"],
["Lightly Row","Traditional","Classical",1,"Relaxing","Piano"],
["Musette in D","J.S. Bach","Classical",1,"Energetic","Piano"],

["Once Upon a Dream","Pyotr Ilyich Tchaikovsky","Film",1,"Relaxing","Piano"],
["Beauty and the Beast","Alan Menken","Film",1,"Emotional","Piano"],
["A Whole New World","Alan Menken","Film",1,"Relaxing","Piano"],
["Can You Feel the Love Tonight","Elton John","Film",1,"Relaxing","Piano"],
["Colors of the Wind","Alan Menken","Film",1,"Emotional","Piano"],

["Remember Me","Kristen Anderson-Lopez","Film",1,"Emotional","Piano"],
["You've Got a Friend in Me","Randy Newman","Film",1,"Energetic","Piano"],
["When You Wish Upon a Star","Leigh Harline","Film",1,"Relaxing","Piano"],
["Married Life (Easy)","Michael Giacchino","Film",1,"Relaxing","Piano"],
["Part of Your World","Alan Menken","Film",1,"Emotional","Piano"],

["Stand by Your Man","Tammy Wynette","Pop",1,"Emotional","Piano"],
["Yesterday","The Beatles","Rock",1,"Emotional","Piano"],
["Hey Jude","The Beatles","Rock",1,"Relaxing","Piano"],
["Imagine Dragons - Bones","Imagine Dragons","Rock",1,"Energetic","Piano"],
["Zombie","The Cranberries","Rock",1,"Emotional","Piano"],

["Wonderful Tonight","Eric Clapton","Rock",1,"Relaxing","Piano"],
["Take Me Home, Country Roads","John Denver","Rock",1,"Relaxing","Piano"],
["Every Breath You Take","The Police","Rock",1,"Relaxing","Piano"],
["Africa","Toto","Rock",1,"Energetic","Piano"],
["The Sound of Silence","Simon & Garfunkel","Rock",1,"Emotional","Piano"],
["La Campanella","Franz Liszt","Classical",5,"Energetic","Piano"],
["Transcendental Etude No.4 'Mazeppa'","Franz Liszt","Classical",5,"Energetic","Piano"],
["Hungarian Rhapsody No.6","Franz Liszt","Classical",5,"Energetic","Piano"],
["Mephisto Waltz No.1","Franz Liszt","Classical",5,"Energetic","Piano"],
["Totentanz","Franz Liszt","Classical",5,"Energetic","Piano"],

["Ballade No.1","Frédéric Chopin","Classical",5,"Emotional","Piano"],
["Ballade No.4","Frédéric Chopin","Classical",5,"Emotional","Piano"],
["Scherzo No.2","Frédéric Chopin","Classical",5,"Energetic","Piano"],
["Etude Op.10 No.1","Frédéric Chopin","Classical",5,"Energetic","Piano"],
["Etude Op.10 No.4","Frédéric Chopin","Classical",5,"Energetic","Piano"],

["Etude Op.10 No.12 'Revolutionary'","Frédéric Chopin","Classical",5,"Energetic","Piano"],
["Etude Op.25 No.11 'Winter Wind'","Frédéric Chopin","Classical",5,"Energetic","Piano"],
["Polonaise Op.53 'Heroic'","Frédéric Chopin","Classical",5,"Energetic","Piano"],
["Fantaisie-Impromptu","Frédéric Chopin","Classical",5,"Energetic","Piano"],
["Piano Sonata No.2","Frédéric Chopin","Classical",5,"Emotional","Piano"],

["Gaspard de la Nuit","Maurice Ravel","Classical",5,"Emotional","Piano"],
["Jeux d'eau","Maurice Ravel","Classical",5,"Relaxing","Piano"],
["Miroirs: Alborada del Gracioso","Maurice Ravel","Classical",5,"Energetic","Piano"],
["Ondine","Maurice Ravel","Classical",5,"Relaxing","Piano"],
["Scarbo","Maurice Ravel","Classical",5,"Energetic","Piano"],

["Toccata in D Minor","J.S. Bach","Classical",5,"Energetic","Piano"],
["Goldberg Variations: Aria","J.S. Bach","Classical",5,"Relaxing","Piano"],
["Italian Concerto","J.S. Bach","Classical",5,"Energetic","Piano"],
["English Suite No.2","J.S. Bach","Classical",5,"Energetic","Piano"],
["Chromatic Fantasia and Fugue","J.S. Bach","Classical",5,"Emotional","Piano"],

["Appassionata Sonata","Ludwig van Beethoven","Classical",5,"Energetic","Piano"],
["Hammerklavier Sonata","Ludwig van Beethoven","Classical",5,"Energetic","Piano"],
["Waldstein Sonata","Ludwig van Beethoven","Classical",5,"Energetic","Piano"],
["Tempest Sonata","Ludwig van Beethoven","Classical",5,"Emotional","Piano"],
["Piano Sonata No.31","Ludwig van Beethoven","Classical",5,"Emotional","Piano"],

["Paganini Etude No.6","Franz Liszt","Classical",5,"Energetic","Piano"],
["Islamey","Mily Balakirev","Classical",5,"Energetic","Piano"],
["Toccata Op.11","Sergei Prokofiev","Classical",5,"Energetic","Piano"],
["Piano Concerto No.2","Sergei Rachmaninoff","Classical",5,"Emotional","Piano"],
["Prelude in G Minor Op.23 No.5","Sergei Rachmaninoff","Classical",5,"Energetic","Piano"],

["Etude-Tableaux Op.39 No.5","Sergei Rachmaninoff","Classical",5,"Energetic","Piano"],
["Sonata in B Minor","Franz Liszt","Classical",5,"Emotional","Piano"],
["Petrushka","Igor Stravinsky","Classical",5,"Energetic","Piano"],
["Spanish Rhapsody","Franz Liszt","Classical",5,"Energetic","Piano"],
["Valse-Fantaisie","Mikhail Glinka","Classical",5,"Energetic","Piano"],
["Honor Him","Hans Zimmer","Film",3,"Emotional","Piano"],
["Now We Are Free","Hans Zimmer","Film",4,"Emotional","Piano"],
["A Small Measure of Peace","Hans Zimmer","Film",4,"Emotional","Piano"],
["Tennessee","Hans Zimmer","Film",3,"Emotional","Piano"],
["This Land","Hans Zimmer","Film",3,"Emotional","Piano"],

["The Ecstasy of Gold","Ennio Morricone","Film",4,"Emotional","Piano"],
["Deborah's Theme","Ennio Morricone","Film",3,"Emotional","Piano"],
["Cinema Paradiso Theme","Ennio Morricone","Film",3,"Emotional","Piano"],

["Concerning Hobbits","Howard Shore","Film",2,"Emotional","Piano"],
["The Breaking of the Fellowship","Howard Shore","Film",4,"Emotional","Piano"],
["Into the West","Howard Shore","Film",3,"Emotional","Piano"],

["The Gravel Road","James Newton Howard","Film",3,"Emotional","Piano"],
["A Window to the Past","John Williams","Film",3,"Emotional","Piano"],
["Leaving Hogwarts","John Williams","Film",2,"Emotional","Piano"],
["Across the Stars","John Williams","Film",4,"Emotional","Piano"],

["The Ludlows","James Horner","Film",4,"Emotional","Piano"],
["For the Love of a Princess","James Horner","Film",3,"Emotional","Piano"],
["My Heart Will Go On","James Horner","Film",2,"Emotional","Piano"],
["Married Life (Simplified)","Michael Giacchino","Film",1,"Emotional","Piano"],
["Theme from Up","Michael Giacchino","Film",1,"Emotional","Piano"],
["Lava","James Ford Murphy","Film",1,"Relaxing","Piano"],
["A Dream Is a Wish Your Heart Makes","Mack David","Film",1,"Emotional","Piano"],
["Circle of Life","Elton John","Film",1,"Energetic","Piano"],

["Hakuna Matata","Elton John","Film",1,"Energetic","Piano"],
["Under the Sea","Alan Menken","Film",1,"Energetic","Piano"],
["Kiss the Girl","Alan Menken","Film",1,"Relaxing","Piano"],

["Wonderwall","Oasis","Rock",1,"Relaxing","Piano"],
["Knockin' on Heaven's Door","Bob Dylan","Rock",1,"Emotional","Piano"],
["Horse with No Name","America","Rock",1,"Relaxing","Piano"],
["Free Fallin'","Tom Petty","Rock",1,"Relaxing","Piano"],
["Wild World","Cat Stevens","Rock",1,"Emotional","Piano"],
["Have You Ever Seen the Rain","Creedence Clearwater Revival","Rock",1,"Relaxing","Piano"],

["Perfect Day","Lou Reed","Pop",1,"Relaxing","Piano"],
["True Colors","Cyndi Lauper","Pop",1,"Emotional","Piano"],
["Beautiful","Christina Aguilera","Pop",1,"Emotional","Piano"],
["I'm Yours","Jason Mraz","Pop",1,"Relaxing","Piano"],
["Home","Phillip Phillips","Pop",1,"Relaxing","Piano"],
["You Raise Me Up","Josh Groban","Pop",1,"Emotional","Piano"],

["Married Life (Full Version)","Michael Giacchino","Film",3,"Emotional","Piano"],
["Bundle of Joy","Michael Giacchino","Film",2,"Emotional","Piano"],
["Rewrite the Stars","Benj Pasek & Justin Paul","Film",2,"Emotional","Piano"],
["City of Stars","Justin Hurwitz","Film",2,"Relaxing","Piano"],
["Mia & Sebastian's Theme","Justin Hurwitz","Film",3,"Emotional","Piano"],
["Another Day of Sun","Justin Hurwitz","Film",4,"Energetic","Piano"],
["The Avengers","Alan Silvestri","Film",3,"Energetic","Piano"],

["Portals","Alan Silvestri","Film",4,"Energetic","Piano"],
["Tale as Old as Time","Alan Menken","Film",2,"Relaxing","Piano"],
["Reflection","Matthew Wilder","Film",2,"Emotional","Piano"],
["Go the Distance","Alan Menken","Film",2,"Emotional","Piano"],
["Married Life Waltz","Michael Giacchino","Film",2,"Relaxing","Piano"],

["Theme from Schindler's List","John Williams","Film",4,"Emotional","Piano"],
["Rey's Theme","John Williams","Film",3,"Relaxing","Piano"],
["Binary Sunset","John Williams","Film",3,"Emotional","Piano"],
["The Force Theme","John Williams","Film",3,"Emotional","Piano"],
["Flying Theme","John Williams","Film",4,"Energetic","Piano"],

["Davy Jones","Hans Zimmer","Film",4,"Emotional","Piano"],
["Flight","Hans Zimmer","Film",3,"Energetic","Piano"],
["Lost But Won","Hans Zimmer","Film",4,"Emotional","Piano"],
["Kiss the Ring","Hans Zimmer","Film",5,"Energetic","Piano"],
["Discombobulate","Hans Zimmer","Film",4,"Energetic","Piano"],

["Counting Stars","OneRepublic","Pop",2,"Energetic","Piano"],
["Firework","Katy Perry","Pop",2,"Energetic","Piano"],
["Roar","Katy Perry","Pop",2,"Energetic","Piano"],
["Stay","Rihanna","Pop",2,"Emotional","Piano"],
["Just the Way You Are","Bruno Mars","Pop",2,"Relaxing","Piano"],

["Grenade","Bruno Mars","Pop",3,"Emotional","Piano"],
["Say You Won't Let Go","James Arthur","Pop",2,"Emotional","Piano"],
["Before You Go","Lewis Capaldi","Pop",2,"Emotional","Piano"],
["Watermelon Sugar","Harry Styles","Pop",2,"Energetic","Piano"],
["As It Was","Harry Styles","Pop",2,"Relaxing","Piano"],

["Numb","Linkin Park","Rock",3,"Emotional","Piano"],
["In the End","Linkin Park","Rock",3,"Energetic","Piano"],
["Fix You (Full Version)","Coldplay","Rock",4,"Emotional","Piano"],
["Adventure of a Lifetime","Coldplay","Rock",3,"Energetic","Piano"],
["Sky Full of Stars","Coldplay","Rock",3,"Energetic","Piano"],

["The Show Must Go On","Queen","Rock",4,"Emotional","Piano"],
["Another One Bites the Dust","Queen","Rock",2,"Energetic","Piano"],
["Don't Stop Me Now","Queen","Rock",3,"Energetic","Piano"],
["Livin' on a Prayer","Bon Jovi","Rock",3,"Energetic","Piano"],
["Dream On","Aerosmith","Rock",4,"Emotional","Piano"],

["The Pink Panther Theme","Henry Mancini","Film",2,"Relaxing","Piano"],
["Married Life (Intermediate)","Michael Giacchino","Film",2,"Emotional","Piano"],
["A Sky Full of Stars","Coldplay","Pop",2,"Energetic","Piano"],
["Someone You Loved (Advanced)","Lewis Capaldi","Pop",4,"Emotional","Piano"],
["Nuvole Bianche (Concert)","Ludovico Einaudi","Classical",5,"Emotional","Piano"],

["Comptine d'un autre été (Concert)","Yann Tiersen","Classical",4,"Relaxing","Piano"],
["Spring","Antonio Vivaldi","Classical",3,"Energetic","Piano"],
["Jesu, Joy of Man's Desiring","J.S. Bach","Classical",2,"Relaxing","Piano"],
["Ave Maria","Franz Schubert","Classical",3,"Emotional","Piano"],
["Dance of the Sugar Plum Fairy","Pyotr Ilyich Tchaikovsky","Classical",3,"Relaxing","Piano"],
["Love Me Like You Do","Ellie Goulding","Pop",2,"Emotional","Piano"],
["Jar of Hearts","Christina Perri","Pop",2,"Emotional","Piano"],
["Fight Song","Rachel Platten","Pop",2,"Energetic","Piano"],
["Apologize","OneRepublic","Pop",2,"Emotional","Piano"],
["Secrets","OneRepublic","Pop",3,"Emotional","Piano"],

["Run","Leona Lewis","Pop",3,"Emotional","Piano"],
["Turning Tables","Adele","Pop",3,"Emotional","Piano"],
["When I Was Your Man","Bruno Mars","Pop",2,"Emotional","Piano"],
["Locked Out of Heaven","Bruno Mars","Pop",3,"Energetic","Piano"],
["See You Again","Wiz Khalifa ft. Charlie Puth","Pop",2,"Emotional","Piano"],

["Attention","Charlie Puth","Pop",2,"Energetic","Piano"],
["We Don't Talk Anymore","Charlie Puth","Pop",2,"Relaxing","Piano"],
["Stay With Me","Sam Smith","Pop",2,"Emotional","Piano"],
["Writing's On The Wall","Sam Smith","Pop",3,"Emotional","Piano"],
["Photograph (Concert Version)","Ed Sheeran","Pop",4,"Emotional","Piano"],

["Boulevard of Broken Dreams","Green Day","Rock",3,"Emotional","Piano"],
["Wake Me Up When September Ends","Green Day","Rock",3,"Emotional","Piano"],
["Iris","Goo Goo Dolls","Rock",3,"Emotional","Piano"],
["With or Without You","U2","Rock",3,"Emotional","Piano"],
["The Unforgiven","Metallica","Rock",4,"Emotional","Piano"],

["November Rain","Guns N' Roses","Rock",4,"Emotional","Piano"],
["Nothing Compares 2 U","Sinéad O'Connor","Rock",3,"Emotional","Piano"],
["Dust in the Wind","Kansas","Rock",2,"Relaxing","Piano"],
["Eye of the Tiger","Survivor","Rock",2,"Energetic","Piano"],
["Carry On Wayward Son","Kansas","Rock",4,"Energetic","Piano"],

["A Game of Thrones","Ramin Djawadi","Film",3,"Emotional","Piano"],
["Light of the Seven","Ramin Djawadi","Film",4,"Emotional","Piano"],
["Westworld Theme","Ramin Djawadi","Film",3,"Relaxing","Piano"],
["Pacific Rim Theme","Ramin Djawadi","Film",4,"Energetic","Piano"],
["Iron Man 3 Theme","Brian Tyler","Film",4,"Energetic","Piano"],

["The Last Samurai","Hans Zimmer","Film",4,"Emotional","Piano"],
["Zooster's Breakout","Hans Zimmer","Film",3,"Energetic","Piano"],
["Pearl Harbor Theme","Hans Zimmer","Film",3,"Emotional","Piano"],
["Spirit","Hans Zimmer","Film",3,"Relaxing","Piano"],
["Brothers","Thomas Newman","Film",3,"Emotional","Piano"],

["American Beauty Theme","Thomas Newman","Film",3,"Relaxing","Piano"],
["The Shape of Water","Alexandre Desplat","Film",3,"Emotional","Piano"],
["The Imitation Game","Alexandre Desplat","Film",3,"Relaxing","Piano"],
["Marion's Theme","John Williams","Film",3,"Emotional","Piano"],
["Theme from E.T.","John Williams","Film",3,"Emotional","Piano"],

["Nocturne in C Sharp Minor","Frédéric Chopin","Classical",4,"Emotional","Piano"],
["Fantaisie in F Minor","Franz Schubert","Classical",5,"Emotional","Piano"],
["Impromptu Op.90 No.3","Franz Schubert","Classical",4,"Relaxing","Piano"],
["Kinderszenen","Robert Schumann","Classical",3,"Relaxing","Piano"],
["Traumerei","Robert Schumann","Classical",3,"Emotional","Piano"],

["Sonata K.545","W.A. Mozart","Classical",3,"Relaxing","Piano"],
["Rondo Alla Turca (Full)","W.A. Mozart","Classical",4,"Energetic","Piano"],
["Piano Concerto No.21","W.A. Mozart","Classical",5,"Relaxing","Piano"],
["Claire de Lune (Concert)","Claude Debussy","Classical",5,"Relaxing","Piano"],
["Children's Corner","Claude Debussy","Classical",4,"Relaxing","Piano"],
["Canon in D","Pachelbel","Classical",2,"Emotional","Violin"],
["Canon in D","Pachelbel","Classical",2,"Emotional","Violin"],
["Ode to Joy","Ludwig van Beethoven","Classical",1,"Energetic","Violin"],
["Twinkle Twinkle Little Star","Traditional","Classical",1,"Relaxing","Violin"],
["Minuet in G","J.S. Bach","Classical",2,"Relaxing","Violin"],
["Für Elise","Ludwig van Beethoven","Classical",2,"Emotional","Violin"],
["Air on the G String","J.S. Bach","Classical",3,"Relaxing","Violin"],
["Ave Maria","Franz Schubert","Classical",3,"Emotional","Violin"],
["The Swan","Camille Saint-Saëns","Classical",3,"Emotional","Violin"],
["Clair de Lune","Claude Debussy","Classical",4,"Relaxing","Violin"],
["Gymnopédie No.1","Erik Satie","Classical",3,"Relaxing","Violin"],
["Nocturne Op.9 No.2","Frédéric Chopin","Classical",4,"Emotional","Violin"],
["Hungarian Dance No.5","Johannes Brahms","Classical",4,"Energetic","Violin"],
["Csárdás","Vittorio Monti","Classical",5,"Energetic","Violin"],
["Spring (The Four Seasons)","Antonio Vivaldi","Classical",3,"Energetic","Violin"],
["Summer (The Four Seasons)","Antonio Vivaldi","Classical",4,"Energetic","Violin"],
["Winter (The Four Seasons)","Antonio Vivaldi","Classical",4,"Emotional","Violin"],
["Violin Concerto No.1","Max Bruch","Classical",5,"Emotional","Violin"],

["Interstellar Theme","Hans Zimmer","Film",4,"Emotional","Violin"],
["Harry Potter Theme","John Williams","Film",2,"Relaxing","Violin"],
["He's a Pirate","Klaus Badelt","Film",3,"Energetic","Violin"],
["Game of Thrones Theme","Ramin Djawadi","Film",3,"Emotional","Violin"],
["Pirates of the Caribbean Theme","Hans Zimmer","Film",3,"Energetic","Violin"],
["The Lord of the Rings Theme","Howard Shore","Film",4,"Emotional","Violin"],
["Schindler's List Theme","John Williams","Film",5,"Emotional","Violin"],
["Merry Go Round of Life","Joe Hisaishi","Film",3,"Relaxing","Violin"],
["Howl's Moving Castle Theme","Joe Hisaishi","Film",3,"Emotional","Violin"],

["Perfect","Ed Sheeran","Pop",2,"Emotional","Violin"],
["A Thousand Years","Christina Perri","Pop",2,"Emotional","Violin"],
["Photograph","Ed Sheeran","Pop",2,"Relaxing","Violin"],
["Someone You Loved","Lewis Capaldi","Pop",2,"Emotional","Violin"],
["Lovely","Billie Eilish","Pop",3,"Emotional","Violin"],
["Shallow","Lady Gaga","Pop",3,"Emotional","Violin"],
["Fix You","Coldplay","Pop",3,"Emotional","Violin"],
["Yellow","Coldplay","Pop",2,"Relaxing","Violin"],
["Viva La Vida","Coldplay","Pop",2,"Energetic","Violin"],

["Clocks","Coldplay","Rock",3,"Relaxing","Violin"],
["The Scientist","Coldplay","Rock",3,"Emotional","Violin"],
["Boulevard of Broken Dreams","Green Day","Rock",3,"Emotional","Violin"],
["Demons","Imagine Dragons","Rock",2,"Emotional","Violin"],
["Believer","Imagine Dragons","Rock",3,"Energetic","Violin"],
["Radioactive","Imagine Dragons","Rock",3,"Energetic","Violin"],
["Numb","Linkin Park","Rock",3,"Emotional","Violin"],
["Nothing Else Matters","Metallica","Rock",4,"Emotional","Violin"],
["Viva La Vida","Coldplay","Rock",2,"Energetic","Violin"],

["Experience","Ludovico Einaudi","Classical",3,"Emotional","Violin"],
["River Flows in You","Yiruma","Classical",2,"Relaxing","Violin"],
["Kiss the Rain","Yiruma","Classical",2,"Relaxing","Violin"],
["He's a Pirate","Klaus Badelt","Film",3,"Energetic","Drums"],
["Interstellar Theme","Hans Zimmer","Film",4,"Emotional","Drums"],
["The Avengers Theme","Alan Silvestri","Film",3,"Energetic","Drums"],
["Star Wars Main Theme","John Williams","Film",3,"Energetic","Drums"],
["Harry Potter Theme","John Williams","Film",2,"Relaxing","Drums"],
["Mission Impossible Theme","Lalo Schifrin","Film",4,"Energetic","Drums"],
["Pirates of the Caribbean Theme","Hans Zimmer","Film",3,"Energetic","Drums"],
["The Dark Knight Theme","Hans Zimmer","Film",4,"Emotional","Drums"],
["James Bond Theme","Monty Norman","Film",3,"Energetic","Drums"],
["Rocky Theme","Bill Conti","Film",2,"Energetic","Drums"],

["Perfect","Ed Sheeran","Pop",2,"Relaxing","Drums"],
["Shape of You","Ed Sheeran","Pop",2,"Energetic","Drums"],
["Counting Stars","OneRepublic","Pop",2,"Energetic","Drums"],
["Viva La Vida","Coldplay","Pop",2,"Energetic","Drums"],
["Yellow","Coldplay","Pop",2,"Relaxing","Drums"],
["Fix You","Coldplay","Pop",3,"Emotional","Drums"],
["Blinding Lights","The Weeknd","Pop",3,"Energetic","Drums"],
["Stay","The Kid LAROI","Pop",3,"Energetic","Drums"],
["Lovely","Billie Eilish","Pop",3,"Emotional","Drums"],
["Someone You Loved","Lewis Capaldi","Pop",2,"Emotional","Drums"],
["A Thousand Years","Christina Perri","Pop",2,"Emotional","Drums"],
["Believer","Imagine Dragons","Pop",3,"Energetic","Drums"],

["We Will Rock You","Queen","Rock",1,"Energetic","Drums"],
["Back In Black","AC/DC","Rock",3,"Energetic","Drums"],
["Smoke on the Water","Deep Purple","Rock",2,"Energetic","Drums"],
["Seven Nation Army","The White Stripes","Rock",2,"Energetic","Drums"],
["Boulevard of Broken Dreams","Green Day","Rock",3,"Emotional","Drums"],
["American Idiot","Green Day","Rock",3,"Energetic","Drums"],
["Numb","Linkin Park","Rock",3,"Emotional","Drums"],
["In The End","Linkin Park","Rock",3,"Energetic","Drums"],
["Nothing Else Matters","Metallica","Rock",4,"Emotional","Drums"],
["Enter Sandman","Metallica","Rock",4,"Energetic","Drums"],
["Californication","Red Hot Chili Peppers","Rock",4,"Relaxing","Drums"],
["Everlong","Foo Fighters","Rock",4,"Energetic","Drums"],
["The Pretender","Foo Fighters","Rock",5,"Energetic","Drums"],
["My Hero","Foo Fighters","Rock",4,"Energetic","Drums"],
["Use Somebody","Kings of Leon","Rock",3,"Emotional","Drums"],
["R U Mine?","Arctic Monkeys","Rock",4,"Energetic","Drums"],
["Do I Wanna Know?","Arctic Monkeys","Rock",4,"Relaxing","Drums"],
["Radioactive","Imagine Dragons","Rock",3,"Energetic","Drums"],
["Demons","Imagine Dragons","Rock",2,"Emotional","Drums"],
["Clocks","Coldplay","Rock",3,"Relaxing","Drums"],
["Romance (Spanish Romance)","Traditional","Classical",2,"Relaxing","Guitar"],
["Asturias","Isaac Albéniz","Classical",5,"Energetic","Guitar"],
["Cavatina","Stanley Myers","Classical",4,"Emotional","Guitar"],
["Lágrima","Francisco Tárrega","Classical",3,"Relaxing","Guitar"],
["Recuerdos de la Alhambra","Francisco Tárrega","Classical",5,"Emotional","Guitar"],
["Malagueña","Traditional","Classical",4,"Energetic","Guitar"],
["Spanish Dance No.5","Enrique Granados","Classical",4,"Energetic","Guitar"],
["Bach Cello Suite No.1 Prelude","J.S. Bach","Classical",4,"Relaxing","Guitar"],

["Interstellar Theme","Hans Zimmer","Film",4,"Emotional","Guitar"],
["He's a Pirate","Klaus Badelt","Film",3,"Energetic","Guitar"],
["Harry Potter Theme","John Williams","Film",2,"Relaxing","Guitar"],
["Game of Thrones Theme","Ramin Djawadi","Film",3,"Emotional","Guitar"],
["Pirates of the Caribbean Theme","Hans Zimmer","Film",3,"Energetic","Guitar"],
["The Lord of the Rings Theme","Howard Shore","Film",4,"Emotional","Guitar"],
["The Last of the Mohicans Theme","Trevor Jones","Film",4,"Emotional","Guitar"],
["Hedwig's Theme","John Williams","Film",2,"Relaxing","Guitar"],

["Perfect","Ed Sheeran","Pop",2,"Relaxing","Guitar"],
["Photograph","Ed Sheeran","Pop",2,"Emotional","Guitar"],
["Shape of You","Ed Sheeran","Pop",2,"Energetic","Guitar"],
["A Thousand Years","Christina Perri","Pop",2,"Emotional","Guitar"],
["Someone You Loved","Lewis Capaldi","Pop",2,"Emotional","Guitar"],
["Lovely","Billie Eilish","Pop",3,"Emotional","Guitar"],
["Stay","The Kid LAROI","Pop",3,"Energetic","Guitar"],
["Blinding Lights","The Weeknd","Pop",3,"Energetic","Guitar"],
["Yellow","Coldplay","Pop",2,"Relaxing","Guitar"],
["Viva La Vida","Coldplay","Pop",2,"Energetic","Guitar"],
["Fix You","Coldplay","Pop",3,"Emotional","Guitar"],

["Wonderwall","Oasis","Rock",2,"Relaxing","Guitar"],
["Knockin' on Heaven's Door","Guns N' Roses","Rock",2,"Relaxing","Guitar"],
["Smoke on the Water","Deep Purple","Rock",2,"Energetic","Guitar"],
["Seven Nation Army","The White Stripes","Rock",2,"Energetic","Guitar"],
["Back In Black","AC/DC","Rock",3,"Energetic","Guitar"],
["Sweet Child O' Mine","Guns N' Roses","Rock",4,"Energetic","Guitar"],
["Nothing Else Matters","Metallica","Rock",4,"Emotional","Guitar"],
["Enter Sandman","Metallica","Rock",4,"Energetic","Guitar"],
["Californication","Red Hot Chili Peppers","Rock",4,"Relaxing","Guitar"],
["Hotel California","Eagles","Rock",5,"Emotional","Guitar"],
["Stairway to Heaven","Led Zeppelin","Rock",5,"Emotional","Guitar"],
["Sweet Home Alabama","Lynyrd Skynyrd","Rock",3,"Energetic","Guitar"],
["Boulevard of Broken Dreams","Green Day","Rock",3,"Emotional","Guitar"],
["American Idiot","Green Day","Rock",3,"Energetic","Guitar"],
["Numb","Linkin Park","Rock",3,"Emotional","Guitar"],
["Do I Wanna Know?","Arctic Monkeys","Rock",4,"Relaxing","Guitar"],
["R U Mine?","Arctic Monkeys","Rock",4,"Energetic","Guitar"],
["Everlong","Foo Fighters","Rock",4,"Energetic","Guitar"],
["O Mio Babbino Caro","Giacomo Puccini","Classical",4,"Emotional","Singing"],
["Ave Maria","Franz Schubert","Classical",3,"Emotional","Singing"],
["Nessun Dorma","Giacomo Puccini","Classical",5,"Energetic","Singing"],
["Hallelujah","Leonard Cohen","Classical",3,"Emotional","Singing"],
["Amazing Grace","Traditional","Classical",2,"Relaxing","Singing"],
["Panis Angelicus","César Franck","Classical",4,"Relaxing","Singing"],
["The Flower Duet","Léo Delibes","Classical",4,"Relaxing","Singing"],

["Interstellar Theme","Hans Zimmer","Film",4,"Emotional","Singing"],
["City of Stars","Justin Hurwitz","Film",3,"Relaxing","Singing"],
["A Million Dreams","The Greatest Showman","Film",2,"Emotional","Singing"],
["This Is Me","The Greatest Showman","Film",3,"Energetic","Singing"],
["Shallow","Lady Gaga","Film",4,"Emotional","Singing"],
["Let It Go","Kristen Anderson-Lopez","Film",2,"Energetic","Singing"],
["Remember Me","Coco","Film",2,"Emotional","Singing"],
["You've Got a Friend in Me","Randy Newman","Film",1,"Relaxing","Singing"],
["Can You Feel the Love Tonight","Elton John","Film",3,"Emotional","Singing"],

["Perfect","Ed Sheeran","Pop",2,"Emotional","Singing"],
["Photograph","Ed Sheeran","Pop",2,"Relaxing","Singing"],
["Shape of You","Ed Sheeran","Pop",2,"Energetic","Singing"],
["Someone You Loved","Lewis Capaldi","Pop",2,"Emotional","Singing"],
["A Thousand Years","Christina Perri","Pop",2,"Emotional","Singing"],
["Lovely","Billie Eilish","Pop",3,"Emotional","Singing"],
["Bad Guy","Billie Eilish","Pop",2,"Energetic","Singing"],
["Stay","The Kid LAROI","Pop",3,"Energetic","Singing"],
["Blinding Lights","The Weeknd","Pop",3,"Energetic","Singing"],
["Viva La Vida","Coldplay","Pop",2,"Energetic","Singing"],
["Yellow","Coldplay","Pop",2,"Relaxing","Singing"],
["Fix You","Coldplay","Pop",3,"Emotional","Singing"],
["Someone Like You","Adele","Pop",3,"Emotional","Singing"],
["Rolling in the Deep","Adele","Pop",4,"Energetic","Singing"],
["When We Were Young","Adele","Pop",4,"Emotional","Singing"],

["Bohemian Rhapsody","Queen","Rock",5,"Energetic","Singing"],
["We Will Rock You","Queen","Rock",2,"Energetic","Singing"],
["Don't Stop Me Now","Queen","Rock",3,"Energetic","Singing"],
["Dream On","Aerosmith","Rock",5,"Emotional","Singing"],
["Nothing Else Matters","Metallica","Rock",4,"Emotional","Singing"],
["Numb","Linkin Park","Rock",3,"Emotional","Singing"],
["Boulevard of Broken Dreams","Green Day","Rock",3,"Emotional","Singing"],
["The Scientist","Coldplay","Rock",3,"Emotional","Singing"],
["Clocks","Coldplay","Rock",3,"Relaxing","Singing"],
["Everlong","Foo Fighters","Rock",4,"Energetic","Singing"],
["Use Somebody","Kings of Leon","Rock",3,"Emotional","Singing"],
["Wonderwall","Oasis","Rock",2,"Relaxing","Singing"],


];
